import expressionSrc from './expression.js?raw';
import minimizeSrc from './minimize.js?raw';

/**
 * Standalone Node script for one Karnaugh problem: the same minimize.js and
 * expression.js the page runs, inlined verbatim (Vite ?raw imports, so the
 * download can never drift from the tool), plus a parameters block and a
 * report. Edit MINTERMS / DONT_CARES and rerun with node.
 */

const HEADER = `/**
 * Karnaugh map minimization, generated by rbt56.com/tools/karnaugh/
 *
 * Self-contained: the functions below are the same code the web tool runs,
 * copied out of its ES modules into one plain script. Change the
 * PARAMETERS block and rerun with:
 *
 *   node karnaugh-solver.js
 */
`;

function inline(src) {
	return src
		.split('\n')
		.filter((line) => !line.startsWith('import '))
		.map((line) => line.replace(/^export (default )?/, ''))
		.join('\n');
}

function paramsBlock({ names, ones, dcs }) {
	return `// =====================================================================
// PARAMETERS - edit these
// =====================================================================
const VARIABLES = ${JSON.stringify(names)}; // first variable = most significant bit of a minterm number
const MINTERMS = ${JSON.stringify(ones)};   // minterms where the function is 1
const DONT_CARES = ${JSON.stringify(dcs)}; // minterms that may be either (never required to be covered)
`;
}

const REPORT = `// =====================================================================
// REPORT
// =====================================================================
const n = VARIABLES.length;
const { sop, pos } = minimizeBoth(n, MINTERMS, DONT_CARES);

function describe(res, label, complement) {
	console.log('='.repeat(72));
	console.log(label);
	console.log('='.repeat(72));
	if (res.constant !== null) {
		console.log('constant function: ' + (complement ? 1 - res.constant : res.constant));
		return;
	}
	console.log('prime implicants (pattern over ' + VARIABLES.join('') + ', - = eliminated):');
	res.primes.forEach((imp, i) => {
		const lits = literals(imp, n, VARIABLES, { complement });
		const term = complement ? sumText(lits) : productText(lits);
		const tag = res.essentialIdx.includes(i) ? '  (essential)' : '';
		console.log('  P' + (i + 1) + ': ' + implicantPattern(imp, n) + '  ' + term + '  cells ' + implicantMinterms(imp, n).join(',') + tag);
	});
	if (res.remaining.length) console.log('left after essentials: cells ' + res.remaining.join(',') + (res.petrick && !res.petrick.exact ? '  (greedy fallback used)' : ''));
	console.log('cover: ' + res.coverIdx.map((i) => 'P' + (i + 1)).join(' + '));
	console.log('terms: ' + res.cover.length + ', literals: ' + literalCount(res.cover));
}

console.log('F(' + VARIABLES.join(', ') + ') = ' + mintermList(MINTERMS, 'Σm') + (DONT_CARES.length ? ' + ' + mintermList(DONT_CARES, 'd') : ''));
console.log();
describe(sop, 'SUM OF PRODUCTS (groups of ones)', false);
console.log('F = ' + sopText(sop.cover, n, VARIABLES));
console.log();
describe(pos, 'PRODUCT OF SUMS (groups of zeros, then De Morgan)', true);
console.log('F = ' + posText(pos.cover, n, VARIABLES));
`;

export function generateScript({ names, ones, dcs }) {
	return [
		HEADER,
		paramsBlock({ names, ones, dcs }),
		'// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n',
		inline(minimizeSrc),
		inline(expressionSrc),
		REPORT
	].join('\n\n');
}
