import amMathSrc from './amMath.js?raw';
import diodeMixerModulatorSrc from './diodeMixerModulator.js?raw';
import envelopeFilterSrc from './envelopeFilter.js?raw';
import eseriesSrc from './eseries.js?raw';
import formatSrc from './format.js?raw';
import jfetModulatorSrc from './jfetModulator.js?raw';
import orderSrc from './order.js?raw';
import rectifierSrc from './rectifier.js?raw';
import sallenKeyLowPassSrc from './sallenKeyLowPass.js?raw';

/**
 * Turns one of this file's own modules into a plain script chunk: strips
 * the `import`/`export` keywords (the download is a single file, so every
 * function just lives in one shared scope) but keeps everything else
 * verbatim - the actual, tested engine source, not a re-typed copy of it.
 */
function inline(src) {
	return src
		.split('\n')
		.filter((line) => !/^import\s/.test(line))
		.join('\n')
		.replace(/^export\s+/gm, '')
		.trim();
}

const HEADER = `/**
 * AM modulator/demodulator design, generated by rbt56.com/tools/am-modulator-demodulator/
 *
 * Self-contained: every function below is the same code the web tool runs,
 * just copied out of its ES modules into one plain script. Change the
 * PARAMETERS block and rerun with:
 *
 *   node am-modulator-demodulator.js
 */
`;

function jfetParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - JFET voltage-controlled-resistor modulator
// =====================================================================

const VP = ${p.vp};                     // V, JFET pinch-off voltage (measured or datasheet, negative for N-channel)
const IDSS = ${p.idss};                  // A, JFET drain current at VGS = 0 (measured or datasheet)
const SWING_FRACTION = ${p.swingFraction};        // fraction of the |VP|/2 gate swing to use (<=1)
const TARGET_MODULATION_INDEX = ${p.targetModulationIndex}; // used to solve for Rb (ignored if RB is set below)
const RB = ${p.rb ?? 'null'};                    // ohms, feedback resistor - set a number to override the solve above
const SOURCE_AMPLITUDE = ${p.sourceAmplitude};       // V, amplitude of the raw modulating source (e.g. 1 V for an Analog Discovery 2)
const FM_MIN = ${p.fmMin};                 // Hz, lowest modulating frequency to pass through the DC-blocking HPF
const VCC = ${p.vcc};                   // V, supply rail used for the DC-bias divider
const RESISTOR_SERIES = 'E24';
`;
}

function jfetReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const design = designJfetModulator({
	vp: VP, idss: IDSS, swingFraction: SWING_FRACTION,
	targetModulationIndex: TARGET_MODULATION_INDEX, rb: RB,
	sourceAmplitude: SOURCE_AMPLITUDE, fmMin: FM_MIN, vcc: VCC, resistorSeries: RESISTOR_SERIES
});
if (!design) { console.log('Invalid parameters (check VP < 0, IDSS > 0, 0 < SWING_FRACTION <= 1).'); } else {
	console.log('='.repeat(72));
	console.log('GAIN CELL');
	console.log('='.repeat(72));
	console.log(\`bias point VC = VP/2 = \${design.vc.toFixed(3)} V, channel resistance at VC = \${design.r1AtCenter.toFixed(1)} ohm\`);
	console.log(\`Rb = \${design.rb.toFixed(1)} ohm  (x = Rb/r1(VC) = \${design.x.toFixed(3)})\`);
	console.log(\`modulation index n = \${design.modulationIndex.toFixed(3)}, nominal gain K0 = \${design.nominalGain.toFixed(3)}\`);
	console.log(\`gate swing: VGS in [\${design.vgsMin.toFixed(3)}, \${design.vgsMax.toFixed(3)}] V, channel R in [\${design.r1Min.toFixed(1)}, \${design.r1Max.toFixed(1)}] ohm\`);

	console.log();
	console.log('='.repeat(72));
	console.log('SIGNAL CONDITIONING CHAIN (source -> gain -> HPF -> summer -> gate)');
	console.log('='.repeat(72));
	const c = design.conditioning;
	console.log(\`gain stage:  Rtop = \${c.gain.rtop} ohm, Rbottom = \${c.gain.rbottom} ohm  (gain = \${c.gain.actual.toFixed(3)}, target \${c.gain.target.toFixed(3)})\`);
	console.log(\`HPF:         R = \${c.hpf.r} ohm, C = \${c.hpf.c.toExponential(4)} F  (cutoff = \${c.hpf.cutoffActual.toFixed(2)} Hz)\`);
	console.log(\`summer:      Rf = Rin = \${c.summer.r} ohm each input, unity gain\`);
	console.log(\`bias divider: Rtop = \${c.divider.top} ohm, Rbottom = \${c.divider.bottom} ohm off \${c.divider.vcc} V  (tap = \${c.divider.actual.toFixed(3)} V, target \${c.divider.target.toFixed(3)} V)\`);

	console.log();
	console.log(design.modulationIndex >= 0.7 && design.modulationIndex <= 1 ? 'modulation index is in the recommended 0.7-1 range.' : 'modulation index is OUTSIDE the recommended 0.7-1 range - raise Rb or the swing fraction.');
}
`;
}

function diodeParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - diode + resonant-tank modulator
// =====================================================================

const FP = ${p.fp};                    // Hz, carrier frequency (tank resonance)
const FM_MAX = ${p.fmMax};                 // Hz, highest modulating frequency to pass
const SIDEBAND_MARGIN = ${p.sidebandMargin};        // >= 1, extra tank bandwidth headroom
const CARRIER_AMPLITUDE = ${p.carrierAmplitude};       // V, for the bias-margin check below
const MOD_AMPLITUDE = ${p.modAmplitude};           // V, for the bias-margin check below
const DIODE_VF = ${p.diodeVf};               // V, diode forward threshold
const BIAS_MARGIN = ${p.biasMargin};             // V, extra headroom above the strict minimum bias
const INDUCTANCE = ${p.inductance};             // H, tank inductor (pick a realistic off-the-shelf value)
const RESISTOR_SERIES = 'E24';
`;
}

function diodeReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const design = designDiodeMixerModulator({
	fp: FP, fmMax: FM_MAX, sidebandMargin: SIDEBAND_MARGIN,
	carrierAmplitude: CARRIER_AMPLITUDE, modAmplitude: MOD_AMPLITUDE,
	diodeVf: DIODE_VF, biasMargin: BIAS_MARGIN, inductance: INDUCTANCE, resistorSeries: RESISTOR_SERIES
});
if (!design) { console.log('Invalid parameters (check FP > 0, FM_MAX > 0, INDUCTANCE > 0).'); } else {
	console.log('='.repeat(72));
	console.log('RESONANT TANK');
	console.log('='.repeat(72));
	console.log(\`target: f0 = \${design.fp} Hz, Q = \${design.q.toFixed(2)}  (BW = \${design.bandwidth.toFixed(1)} Hz = 2 x margin x fmMax)\`);
	console.log(\`L = \${design.inductance.toExponential(4)} H (chosen), C = \${design.capacitance.toExponential(4)} F, R = \${design.resistance.toFixed(1)} ohm\`);
	console.log(\`actual: f0 = \${design.f0Actual.toFixed(1)} Hz, Q = \${design.qActual.toFixed(2)}, BW = \${design.bwActual.toFixed(1)} Hz\`);
	if (design.requiredBias != null) {
		console.log();
		console.log(\`required DC bias >= \${design.requiredBias.toFixed(2)} V (carrier + modulant amplitudes + diode Vf + margin)\`);
	}
}
`;
}

function demodParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - envelope demodulator (rectifier + low-pass filter)
// =====================================================================

const RECTIFIER_TYPE = ${JSON.stringify(p.rectifierType)}; // 'full' or 'half'
const FP_CARRIER = ${p.fpCarrier};             // Hz, carrier frequency
const FM_MAX = ${p.fmMax};                 // Hz, highest modulating frequency to recover
const AMAX_DB = ${p.amaxDb};                // dB, max attenuation allowed up to FM_MAX
const AMIN_DB = ${p.aminDb};                // dB, min attenuation required at the ripple frequency
const ORDER = ${p.order ?? 'null'};                  // set to null to use the minimum even order that meets the spec
const RESPONSE = ${JSON.stringify(p.response)};      // 'butterworth' or 'chebyshev'
const RESISTOR_SERIES = 'E24';
`;
}

function demodReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const rippleHz = RECTIFIER_TYPE === 'full' ? 2 * FP_CARRIER : FP_CARRIER;
const rectifier = RECTIFIER_TYPE === 'full' ? designPrecisionRectifier({}) : designHalfWaveRectifier({});
console.log('='.repeat(72));
console.log('RECTIFIER (' + RECTIFIER_TYPE + '-wave)');
console.log('='.repeat(72));
console.log(RECTIFIER_TYPE === 'full'
	? \`precision full-wave: R1=R2=R3=\${rectifier.r1} ohm, diode \${rectifier.diode}. Ripple fundamental at 2 x fp = \${rippleHz} Hz.\`
	: \`half-wave: single diode \${rectifier.diode}. Ripple fundamental at fp = \${rippleHz} Hz.\`);

console.log();
console.log('='.repeat(72));
console.log('ENVELOPE LOW-PASS FILTER');
console.log('='.repeat(72));
const design = designEnvelopeLowPass({ response: RESPONSE, amaxDb: AMAX_DB, aminDb: AMIN_DB, fp: FM_MAX, fs: rippleHz, order: ORDER, resistorSeries: RESISTOR_SERIES });
console.log(\`k = fp/fs = \${design.k.toFixed(4)}, minimum order >= \${design.minOrder.toFixed(2)} -> using n = \${design.n}\`);
design.realized.forEach((r, i) => {
	const f0Target = design.stages[i].wn / (2 * Math.PI);
	const f0Actual = r.actual.wn / (2 * Math.PI);
	console.log(\`stage \${i + 1}: target f0 = \${f0Target.toFixed(1)} Hz, Q = \${design.stages[i].q.toFixed(4)}\`);
	console.log(\`  R = \${r.components.R1} ohm, Ctop = \${r.components.Ctop.toExponential(4)} F, Cbottom = \${r.components.Cbottom.toExponential(4)} F\`);
	console.log(\`  actual f0 = \${f0Actual.toFixed(1)} Hz (\${(100 * (f0Actual - f0Target) / f0Target).toFixed(2)}%), Q = \${r.actual.q.toFixed(4)}\`);
});
`;
}

const ENGINE = [
	eseriesSrc,
	formatSrc,
	orderSrc,
	sallenKeyLowPassSrc,
	envelopeFilterSrc,
	jfetModulatorSrc,
	diodeMixerModulatorSrc,
	rectifierSrc,
	amMathSrc
]
	.map(inline)
	.join('\n\n');

export function generateJfetScript(params) {
	return [HEADER, jfetParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, jfetReportBlock()].join('\n\n');
}

export function generateDiodeScript(params) {
	return [HEADER, diodeParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, diodeReportBlock()].join('\n\n');
}

export function generateDemodScript(params) {
	return [HEADER, demodParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, demodReportBlock()].join('\n\n');
}
