import amMathSrc from './amMath.js?raw';
import diodeMixerModulatorSrc from './diodeMixerModulator.js?raw';
import envelopeFilterSrc from './envelopeFilter.js?raw';
import eseriesSrc from './eseries.js?raw';
import formatSrc from './format.js?raw';
import jfetModelSrc from './jfetModel.js?raw';
import jfetModulatorSrc from './jfetModulator.js?raw';
import orderSrc from './order.js?raw';
import rectifierSrc from './rectifier.js?raw';
import sallenKeyLowPassSrc from './sallenKeyLowPass.js?raw';

/**
 * Turns one of this file's own modules into a plain script chunk: strips
 * the `import`/`export` keywords (the download is a single file, so every
 * function just lives in one shared scope) but keeps everything else
 * verbatim - the actual, tested engine source, not a re-typed copy of it.
 */
function inline(src) {
	return src
		.split('\n')
		.filter((line) => !/^import\s/.test(line))
		.join('\n')
		.replace(/^export\s+/gm, '')
		.trim();
}

const HEADER = `/**
 * AM modulator/demodulator design, generated by rbt56.com/tools/am-modulator-demodulator/
 *
 * Self-contained: every function below is the same code the web tool runs,
 * just copied out of its ES modules into one plain script. Change the
 * PARAMETERS block and rerun with:
 *
 *   node am-modulator-demodulator.js
 */
`;

function jfetParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - JFET voltage-controlled-resistor modulator
// =====================================================================

// Where the JFET's line G(VGS) = beta (VGS - VP) comes from: 'idss' uses
// VP and IDSS, 'rdson' uses VP and RDS_ON, 'measured' fits a line to the
// MEASUREMENTS rows ([VGS, rDS] pairs) inside the WINDOW.
const JFET_MODE = ${JSON.stringify(p.mode ?? 'idss')};
const VP = ${p.vp};                     // V, JFET pinch-off voltage (negative for N-channel)
const IDSS = ${p.idss};                  // A, drain current at VGS = 0 (used in 'idss' mode)
const RDS_ON = ${p.rdsOn ?? 'null'};                // ohm, channel resistance at VGS = 0 (used in 'rdson' mode)
const MEASUREMENTS = ${p.measurements ? JSON.stringify(p.measurements) : 'null'}; // [[VGS, rDS], ...] (used in 'measured' mode)
const WINDOW = { low: ${p.windowLow ?? 'null'}, high: ${p.windowHigh ?? 'null'} }; // V, the VGS stretch the fit and the design use
// 'noninverting': JFET in the feedback divider, one op-amp, n = s x/(1+x).
// 'inverting': JFET as the input resistor behind a follower, n = s exactly,
// small x, a post-gain stage brings the output up to TARGET_OUTPUT_AMPLITUDE.
const TOPOLOGY = ${JSON.stringify(p.topology ?? 'noninverting')};
const TARGET_OUTPUT_AMPLITUDE = ${p.targetOutputAmplitude ?? 1}; // V, inverting cell only
const CARRIER_BUFFER = ${p.carrierBuffer === false ? 'false' : 'true'};          // inverting cell only: follower between the divider and the channel
const SWING_FRACTION = ${p.swingFraction};        // fraction of the |VP|/2 gate swing to use (<=1)
const TARGET_MODULATION_INDEX = ${p.targetModulationIndex}; // used to solve for Rb (ignored if RB is set below)
const RB = ${p.rb ?? 'null'};                    // ohms, feedback resistor - set a number to override the solve above
const SOURCE_AMPLITUDE = ${p.sourceAmplitude};       // V, amplitude of the raw modulating source (e.g. 1 V for an Analog Discovery 2)
const FM_MIN = ${p.fmMin};                 // Hz, lowest modulating frequency to pass through the DC-blocking HPF
const VCC = ${p.vcc};                   // V, supply rail (the gate-drive summer takes its bias from +VCC)
const FP = ${p.fp};                 // Hz, carrier frequency: what the op-amp has to keep up with
const CARRIER_SOURCE_AMPLITUDE = ${p.carrierSourceAmplitude}; // V, amplitude of the raw carrier source
const CARRIER_MARGIN = ${p.carrierMargin};          // fraction of the triode limit the carrier may use
const OPAMP_SWING = ${p.opampSwing};           // V, output swing the op-amp reaches on this supply (Vcc - 1.5 for a TL08x)
const GBW = ${p.gbw};                  // Hz, op-amp gain-bandwidth product (3e6 for a TL08x)
const SLEW_RATE = ${p.slewRate};         // V/s, op-amp slew rate (13e6 for a TL08x)
const RESISTOR_SERIES = 'E24';
`;
}

function jfetReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const jfetModel =
	JFET_MODE === 'rdson'
		? modelFromRdsOn(VP, RDS_ON)
		: JFET_MODE === 'measured'
			? fitModel((MEASUREMENTS || []).map(([vgs, rds]) => ({ vgs, rds, g: 1 / rds })), WINDOW)
			: modelFromIdss(VP, IDSS);
if (!jfetModel) {
	console.log('No usable JFET line: check JFET_MODE and the figures or measurements that go with it.');
	process.exit(1);
}
console.log('='.repeat(72));
console.log('JFET LINE  G(VGS) = beta (VGS - VP)');
console.log('='.repeat(72));
console.log(\`mode ${'$'}{jfetModel.mode}: VP = ${'$'}{jfetModel.vp.toFixed(3)} V, beta = ${'$'}{(jfetModel.beta * 1000).toFixed(4)} mS/V, implied IDSS = ${'$'}{(jfetModel.idss * 1000).toFixed(2)} mA, rDS(on) = ${'$'}{jfetModel.rdsOn.toFixed(1)} ohm\`);
if (jfetModel.fit) console.log(\`fit over ${'$'}{jfetModel.fit.count} points in [${'$'}{jfetModel.fit.low}, ${'$'}{jfetModel.fit.high}] V: R^2 = ${'$'}{jfetModel.fit.r2.toFixed(4)}, largest deviation ${'$'}{(100 * jfetModel.fit.maxDev).toFixed(1)}% at ${'$'}{jfetModel.fit.maxDevAt} V\`);
console.log(\`bias point VC = ${'$'}{jfetModel.vc.toFixed(3)} V, half-range ${'$'}{jfetModel.halfRange.toFixed(3)} V\`);
console.log();

const design = designJfetModulator({
	model: jfetModel, topology: TOPOLOGY, targetOutputAmplitude: TARGET_OUTPUT_AMPLITUDE, carrierBuffer: CARRIER_BUFFER, swingFraction: SWING_FRACTION,
	targetModulationIndex: TARGET_MODULATION_INDEX, rb: RB,
	sourceAmplitude: SOURCE_AMPLITUDE, fmMin: FM_MIN, vcc: VCC,
	fp: FP, carrierSourceAmplitude: CARRIER_SOURCE_AMPLITUDE, carrierMargin: CARRIER_MARGIN,
	opampSwing: OPAMP_SWING, gbw: GBW, slewRate: SLEW_RATE, resistorSeries: RESISTOR_SERIES
});
if (!design) {
	const ceiling = conductanceDepth(jfetModel, SWING_FRACTION);
	console.log(ceiling === null ? 'The swing pinches the channel off: lower SWING_FRACTION or narrow the window.' : 'The target modulation index cannot exceed the conductance depth s = ' + ceiling.toFixed(3) + ' for this swing: lower TARGET_MODULATION_INDEX or widen the swing.');
} else {
	console.log('='.repeat(72));
	console.log('GAIN CELL (' + TOPOLOGY + ')');
	console.log('='.repeat(72));
	console.log(\`bias point VC = \${design.vc.toFixed(3)} V, channel resistance at VC = \${design.r1AtCenter.toFixed(1)} ohm, conductance depth s = \${design.gDepth.toFixed(3)}\`);
	console.log(\`\${TOPOLOGY === 'inverting' ? 'R2' : 'Rb'} = \${design.feedback.toFixed(1)} ohm  (x = \${design.x.toFixed(3)})\`);
	console.log(\`modulation index n = \${design.modulationIndex.toFixed(3)}, gain at bias K0 = \${design.nominalGain.toFixed(3)}, signal gain \${design.gainMin.toFixed(3)} .. \${design.gainMax.toFixed(3)}\`);
	console.log(\`gate swing: VGS in [\${design.vgsMin.toFixed(3)}, \${design.vgsMax.toFixed(3)}] V, channel R in [\${design.r1Min.toFixed(1)}, \${design.r1Max.toFixed(1)}] ohm\`);
	if (design.buffer) {
		const b = design.buffer;
		console.log(\`carrier follower \${b.enabled ? 'ON' : 'OFF'}: with it (Zs = \${b.zOut} ohm) n_eff \${b.withBuffer.effectiveModulationIndex.toFixed(3)}, THD \${(100 * b.withBuffer.thd).toFixed(2)}%; without it (divider \${b.dividerImpedance.toFixed(0)} ohm) n_eff \${b.withoutBuffer.effectiveModulationIndex.toFixed(3)}, THD \${(100 * b.withoutBuffer.thd).toFixed(1)}%\`);
	}
	if (design.postGain && design.postGain.needed) {
		const pg = design.postGain;
		console.log(\`post-gain stage: K = \${pg.kActual.toFixed(2)} (Rtop \${pg.rtop} ohm, Rbottom \${pg.rbottom} ohm), loss at fp \${pg.factor.toFixed(4)} (constant), output \${pg.outputAmplitude.toFixed(3)} V, envelope max \${pg.envelopeMax.toFixed(2)} V \${pg.swingOk ? '' : '(OVER THE SWING) '}slew \${(pg.slewNeeded / 1e6).toFixed(2)} V/us \${pg.slewOk ? '' : '(TOO FAST)'}\`);
	}

	console.log();
	console.log('='.repeat(72));
	console.log('CARRIER PATH');
	console.log('='.repeat(72));
	const c = design.carrier;
	console.log(\`triode limit VGS_min - VP = \${c.vdsSat.toFixed(3)} V -> carrier at most \${c.acTriode.toFixed(3)} V (margin \${c.margin}); op-amp limit \${c.acOpamp.toFixed(3)} V; limiting: \${c.limit}\`);
	console.log(c.divider.top > 0 ? \`carrier divider: \${c.divider.top} ohm / \${c.divider.bottom} ohm -> Ac = \${c.ac.toFixed(4)} V (drives the + input, no buffer)\` : \`no divider needed, Ac = \${c.ac.toFixed(4)} V\`);
	console.log(\`output carrier K0*Ac = \${c.carrierOut.toFixed(3)} V, envelope \${c.envelopeMin.toFixed(3)} .. \${c.envelopeMax.toFixed(3)} V, peak current \${(c.jfetPeakCurrent * 1000).toFixed(2)} mA\`);
	console.log(\`VDS^2 term: DC offset and 2fp tone of \${(c.tone2fp * 1000).toFixed(1)} mV (\${c.tone2fpDbc.toFixed(1)} dBc) at \${c.tone2fpHz} Hz, no envelope distortion\`);

	console.log();
	console.log('='.repeat(72));
	console.log('OP-AMP LIMITS AT THE CARRIER');
	console.log('='.repeat(72));
	const o = design.opamp;
	console.log(\`K trough/bias/crest = \${o.kTrough.toFixed(2)} / \${o.kNominal.toFixed(2)} / \${o.kCrest.toFixed(2)}, closed-loop BW \${(o.bwTrough / 1000).toFixed(0)} / \${(o.bwNominal / 1000).toFixed(0)} / \${(o.bwCrest / 1000).toFixed(0)} kHz\`);
	console.log(\`gain factor at fp: \${o.factorTrough.toFixed(4)} / \${o.factorNominal.toFixed(3)} / \${o.factorCrest.toFixed(3)} -> n effective \${o.effectiveModulationIndex.toFixed(3)} (designed \${design.modulationIndex.toFixed(3)}), audio THD \${(100 * o.thd).toFixed(2)}%\`);
	console.log(\`fp*Kmax/GBW = \${o.gbwRatio.toFixed(2)} \${o.gbwOk ? '<= 0.2, fine' : o.rbLimit ? '> 0.2: set the feedback resistor to ' + o.rbLimit + ' ohm (n = ' + o.nAtLimit.toFixed(3) + '), or a faster op-amp / lower carrier' : '> 0.2 and no feedback resistor fixes it: faster op-amp or lower carrier'}\`);
	console.log(\`op-amps in the modulator: \${o.opampCount} (summer included)\`);
	console.log(\`slew: needs \${(o.slewNeeded / 1e6).toFixed(2)} V/us, half of SR is \${(o.slewRate / 2e6).toFixed(1)} V/us -> \${o.slewOk ? 'fine' : 'TOO FAST, lower the carrier'}\`);

	console.log();
	console.log('='.repeat(72));
	console.log('GATE DRIVE (one inverting summer: series C + Rac from the source, Rbias from +Vcc, Rf)');
	console.log('='.repeat(72));
	const sm = design.conditioning.summer;
	console.log(\`Rf = \${sm.rf} ohm, Rac = \${sm.rac} ohm (gain \${sm.gainActual.toFixed(3)}, target \${sm.gainTarget.toFixed(3)}), Rbias = \${sm.rbias} ohm (bias \${sm.biasActual.toFixed(3)} V, target -\${sm.biasTarget.toFixed(3)} V)\`);
	console.log(\`C = \${sm.c.toExponential(2)} F -> high-pass corner \${sm.fcActual.toFixed(1)} Hz (target \${sm.fcTarget.toFixed(1)} Hz); most negative gate voltage \${sm.outMin.toFixed(2)} V vs swing \${sm.opampSwing} V -> \${sm.headroomOk ? 'fits' : 'DOES NOT FIT: raise Vcc or use a smaller |VP|'}\`);

	console.log();
	console.log(design.modulationIndex >= 0.7 && design.modulationIndex <= 1 ? 'modulation index is in the recommended 0.7-1 range.' : 'modulation index is OUTSIDE the recommended 0.7-1 range - raise Rb or the swing fraction.');
}
`;
}

function diodeParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - diode + resonant-tank modulator
// =====================================================================

const FP = ${p.fp};                    // Hz, carrier frequency (tank resonance)
const FM_MAX = ${p.fmMax};                 // Hz, highest modulating frequency to pass
const SIDEBAND_MARGIN = ${p.sidebandMargin};        // >= 1, extra tank bandwidth headroom
const CARRIER_AMPLITUDE = ${p.carrierAmplitude};       // V, for the bias-margin check below
const MOD_AMPLITUDE = ${p.modAmplitude};           // V, for the bias-margin check below
const DIODE_VF = ${p.diodeVf};               // V, diode forward threshold
const BIAS_MARGIN = ${p.biasMargin};             // V, extra headroom above the strict minimum bias
const INDUCTANCE = ${p.inductance};             // H, tank inductor (pick a realistic off-the-shelf value)
const RESISTOR_SERIES = 'E24';
`;
}

function diodeReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const design = designDiodeMixerModulator({
	fp: FP, fmMax: FM_MAX, sidebandMargin: SIDEBAND_MARGIN,
	carrierAmplitude: CARRIER_AMPLITUDE, modAmplitude: MOD_AMPLITUDE,
	diodeVf: DIODE_VF, biasMargin: BIAS_MARGIN, inductance: INDUCTANCE, resistorSeries: RESISTOR_SERIES
});
if (!design) { console.log('Invalid parameters (check FP > 0, FM_MAX > 0, INDUCTANCE > 0).'); } else {
	console.log('='.repeat(72));
	console.log('RESONANT TANK');
	console.log('='.repeat(72));
	console.log(\`target: f0 = \${design.fp} Hz, Q = \${design.q.toFixed(2)}  (BW = \${design.bandwidth.toFixed(1)} Hz = 2 x margin x fmMax)\`);
	console.log(\`L = \${design.inductance.toExponential(4)} H (chosen), C = \${design.capacitance.toExponential(4)} F, R = \${design.resistance.toFixed(1)} ohm\`);
	console.log(\`actual: f0 = \${design.f0Actual.toFixed(1)} Hz, Q = \${design.qActual.toFixed(2)}, BW = \${design.bwActual.toFixed(1)} Hz\`);
	if (design.requiredBias != null) {
		console.log();
		console.log(\`required DC bias >= \${design.requiredBias.toFixed(2)} V (carrier + modulant amplitudes + diode Vf + margin)\`);
	}
}
`;
}

function demodParamsBlock(p) {
	return `// =====================================================================
// PARAMETERS - envelope demodulator (rectifier + low-pass filter)
// =====================================================================

const RECTIFIER_TYPE = ${JSON.stringify(p.rectifierType)}; // 'full' or 'half'
const FP_CARRIER = ${p.fpCarrier};             // Hz, carrier frequency
const FM_MAX = ${p.fmMax};                 // Hz, highest modulating frequency to recover
const AMAX_DB = ${p.amaxDb};                // dB, max attenuation allowed up to FM_MAX
const AMIN_DB = ${p.aminDb};                // dB, min attenuation required at the ripple frequency
const ORDER = ${p.order ?? 'null'};                  // set to null to use the minimum even order that meets the spec
const RESPONSE = ${JSON.stringify(p.response)};      // 'butterworth' or 'chebyshev'
const RESISTOR_SERIES = 'E24';
`;
}

function demodReportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

const rippleHz = RECTIFIER_TYPE === 'full' ? 2 * FP_CARRIER : FP_CARRIER;
const rectifier = RECTIFIER_TYPE === 'full' ? designPrecisionRectifier({}) : designHalfWaveRectifier({});
console.log('='.repeat(72));
console.log('RECTIFIER (' + RECTIFIER_TYPE + '-wave)');
console.log('='.repeat(72));
console.log(RECTIFIER_TYPE === 'full'
	? \`precision full-wave: R1=R2=R3=\${rectifier.r1} ohm, diode \${rectifier.diode}. Ripple fundamental at 2 x fp = \${rippleHz} Hz.\`
	: \`half-wave: single diode \${rectifier.diode}. Ripple fundamental at fp = \${rippleHz} Hz.\`);

console.log();
console.log('='.repeat(72));
console.log('ENVELOPE LOW-PASS FILTER');
console.log('='.repeat(72));
const design = designEnvelopeLowPass({ response: RESPONSE, amaxDb: AMAX_DB, aminDb: AMIN_DB, fp: FM_MAX, fs: rippleHz, order: ORDER, resistorSeries: RESISTOR_SERIES });
console.log(\`k = fp/fs = \${design.k.toFixed(4)}, minimum order >= \${design.minOrder.toFixed(2)} -> using n = \${design.n}\`);
design.realized.forEach((r, i) => {
	const f0Target = design.stages[i].wn / (2 * Math.PI);
	const f0Actual = r.actual.wn / (2 * Math.PI);
	console.log(\`stage \${i + 1}: target f0 = \${f0Target.toFixed(1)} Hz, Q = \${design.stages[i].q.toFixed(4)}\`);
	console.log(\`  R = \${r.components.R1} ohm, Ctop = \${r.components.Ctop.toExponential(4)} F, Cbottom = \${r.components.Cbottom.toExponential(4)} F\`);
	console.log(\`  actual f0 = \${f0Actual.toFixed(1)} Hz (\${(100 * (f0Actual - f0Target) / f0Target).toFixed(2)}%), Q = \${r.actual.q.toFixed(4)}\`);
});
`;
}

const ENGINE = [
	eseriesSrc,
	formatSrc,
	orderSrc,
	sallenKeyLowPassSrc,
	envelopeFilterSrc,
	jfetModelSrc,
	jfetModulatorSrc,
	diodeMixerModulatorSrc,
	rectifierSrc,
	amMathSrc
]
	.map(inline)
	.join('\n\n');

export function generateJfetScript(params) {
	return [HEADER, jfetParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, jfetReportBlock()].join('\n\n');
}

export function generateDiodeScript(params) {
	return [HEADER, diodeParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, diodeReportBlock()].join('\n\n');
}

export function generateDemodScript(params) {
	return [HEADER, demodParamsBlock(params), '// =====================================================================\n// ENGINE - same code the web tool runs\n// =====================================================================\n', ENGINE, demodReportBlock()].join('\n\n');
}
