import bodeSrc from './bode.js?raw';
import eseriesSrc from './eseries.js?raw';
import firstOrderSrc from './firstOrder.js?raw';
import firstOrderHighPassSrc from './firstOrderHighPass.js?raw';
import formatSrc from './format.js?raw';
import mfbSrc from './mfb.js?raw';
import mfbHighPassSrc from './mfbHighPass.js?raw';
import orderSrc from './order.js?raw';
import sallenKeySrc from './sallenKey.js?raw';
import sallenKeyHighPassSrc from './sallenKeyHighPass.js?raw';
import sensitivitySrc from './sensitivity.js?raw';
import stagesSrc from './stages.js?raw';

/**
 * Turns one of this file's own modules into a plain script chunk: strips
 * the `import`/`export` keywords (the download is a single file, so every
 * function just lives in one shared scope) but keeps everything else
 * verbatim. This is the actual, tested engine source - not a re-typed copy
 * of it - so the download can never drift from what the page itself computes.
 */
function inline(src) {
	return src
		.split('\n')
		.filter((line) => !/^import\s/.test(line))
		.join('\n')
		.replace(/^export\s+/gm, '')
		.trim();
}

const TYPE_LABEL = {
	lowpass: 'low-pass',
	highpass: 'high-pass',
	bandpass: 'band-pass',
	bandstop: 'band-stop'
};

function header(filterType) {
	return `/**
 * Active ${TYPE_LABEL[filterType] ?? 'low-pass'} filter design, generated by rbt56.com/tools/filter-design/
 *
 * Self-contained: every function below is the same code the web tool runs,
 * just copied out of its ES modules into one plain script. Change the
 * PARAMETERS block and rerun with:
 *
 *   node filter-design.js
 *
 * Everything downstream of PARAMETERS recomputes from scratch, same as the
 * page does live as its form is edited.
 */
`;
}

function paramsBlock({ amaxDb, aminDb, fp, fs, fl, fh, fsl, fsh, filterType, response, topology, order, orderHp, orderLp, capOverrides }) {
	const hasOverrides = capOverrides && Object.keys(capOverrides).length > 0;
	return `// =====================================================================
// PARAMETERS - the only block meant to be edited
// =====================================================================

const Amax = ${amaxDb};              // dB, max attenuation allowed in the passband
const Amin = ${aminDb};              // dB, min attenuation required in the stopband
const FILTER_TYPE = ${JSON.stringify(filterType)}; // 'lowpass', 'highpass', 'bandpass' or 'bandstop'
const RESPONSE  = ${JSON.stringify(response)};  // 'butterworth' or 'chebyshev'
const TOPOLOGY  = ${JSON.stringify(topology)};       // 'mfb' or 'sallenKey'
const RESISTOR_SERIES = 'E24';    // 'E24' or 'E96'
const SUMMING_R = 10000;          // ohms, band-stop's summing amplifier (any equal value works)

// Used when FILTER_TYPE is 'lowpass' or 'highpass':
const fp   = ${fp};           // Hz, passband edge (the higher edge for a high-pass)
const fs   = ${fs};           // Hz, stopband edge (the lower edge for a high-pass)
const ORDER = ${order};                 // set to null to use the minimum order that meets the spec

// Used when FILTER_TYPE is 'bandpass' (a high-pass section cascaded with a
// low-pass section - see designBandPass below) or 'bandstop' (a low-pass
// branch and a high-pass branch summed instead - see designBandStop).
// Band-pass needs fsl < fl < fh < fsh; band-stop needs fl < fsl < fsh < fh.
const fl   = ${fl};           // Hz
const fh   = ${fh};           // Hz
const fsl  = ${fsl};           // Hz
const fsh  = ${fsh};           // Hz
const ORDER_HP = ${orderHp};                 // set to null to use the minimum order for the high-pass section/branch
const ORDER_LP = ${orderLp};                 // set to null to use the minimum order for the low-pass section/branch

// Capacitor values (farads) to use instead of the automatic search, keyed
// by stage index (0-based, same order as the STAGES report below). Leave a
// stage out of this object to keep searching automatically for it. Needs
// C1 and C2 for an MFB stage, Ctop and Cbottom for Sallen-Key, C for a
// first-order (leftover, odd-n) stage.
const CAP_OVERRIDES = ${hasOverrides ? JSON.stringify(capOverrides, null, 2) : '{}'};
`;
}

function reportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

console.log('='.repeat(72));
console.log('ORDER');
console.log('='.repeat(72));

let design;
if (FILTER_TYPE === 'bandpass') {
	const kHp = transitionRatio(fsl, fl);
	const minOrderHp = RESPONSE === 'chebyshev' ? chebyshevOrder(Amax, Amin, kHp) : butterworthOrder(Amax, Amin, kHp);
	const nHp = ORDER_HP ?? Math.max(1, Math.ceil(minOrderHp));
	const kLp = transitionRatio(fh, fsh);
	const minOrderLp = RESPONSE === 'chebyshev' ? chebyshevOrder(Amax, Amin, kLp) : butterworthOrder(Amax, Amin, kLp);
	const nLp = ORDER_LP ?? Math.max(1, Math.ceil(minOrderLp));
	console.log(\`spec: Amax=\${Amax} dB, Amin=\${Amin} dB, \${RESPONSE}, bandpass (fl=\${fl} fh=\${fh} fsl=\${fsl} fsh=\${fsh} Hz)\`);
	console.log(\`high-pass side: k = fsl/fl = \${kHp.toFixed(4)}, minimum order >= \${minOrderHp.toFixed(4)} -> using n = \${nHp}\`);
	console.log(\`low-pass side:  k = fh/fsh = \${kLp.toFixed(4)}, minimum order >= \${minOrderLp.toFixed(4)} -> using n = \${nLp}\`);
	design = designBandPass({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fl, fh, fsl, fsh, orderHigh: nHp, orderLow: nLp });
} else if (FILTER_TYPE === 'bandstop') {
	const kLp = transitionRatio(fl, fsl);
	const minOrderLp = RESPONSE === 'chebyshev' ? chebyshevOrder(Amax, Amin, kLp) : butterworthOrder(Amax, Amin, kLp);
	const nLp = ORDER_LP ?? Math.max(1, Math.ceil(minOrderLp));
	const kHp = transitionRatio(fsh, fh);
	const minOrderHp = RESPONSE === 'chebyshev' ? chebyshevOrder(Amax, Amin, kHp) : butterworthOrder(Amax, Amin, kHp);
	const nHp = ORDER_HP ?? Math.max(1, Math.ceil(minOrderHp));
	console.log(\`spec: Amax=\${Amax} dB, Amin=\${Amin} dB, \${RESPONSE}, bandstop (fl=\${fl} fsl=\${fsl} fsh=\${fsh} fh=\${fh} Hz)\`);
	console.log(\`low-pass branch:  k = fl/fsl = \${kLp.toFixed(4)}, minimum order >= \${minOrderLp.toFixed(4)} -> using n = \${nLp}\`);
	console.log(\`high-pass branch: k = fsh/fh = \${kHp.toFixed(4)}, minimum order >= \${minOrderHp.toFixed(4)} -> using n = \${nHp}\`);
	design = designBandStop({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fl, fh, fsl, fsh, orderHigh: nHp, orderLow: nLp });
} else {
	const k = FILTER_TYPE === 'highpass' ? transitionRatio(fs, fp) : transitionRatio(fp, fs);
	const minOrder = RESPONSE === 'chebyshev' ? chebyshevOrder(Amax, Amin, k) : butterworthOrder(Amax, Amin, k);
	const n = ORDER ?? Math.max(1, Math.ceil(minOrder));
	console.log(\`spec: Amax=\${Amax} dB at \${fp} Hz, Amin=\${Amin} dB at \${fs} Hz, \${RESPONSE}, \${FILTER_TYPE}\`);
	console.log(FILTER_TYPE === 'highpass' ? \`k = fs/fp = \${k.toFixed(4)}\` : \`k = fp/fs = \${k.toFixed(4)}\`);
	console.log(\`minimum order >= \${minOrder.toFixed(4)} -> using n = \${n}\`);
	design =
		FILTER_TYPE === 'highpass'
			? designHighPass({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fp, fs, order: n })
			: designLowPass({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fp, fs, order: n });
	if (RESPONSE === 'butterworth') {
		// Where Amax reaches the components: the pole circle (= the -3 dB point)
		// sits at fp * eps^(-1/n) for a low-pass, fp * eps^(+1/n) for a high-pass,
		// so that exactly Amax dB is lost at fp. eps = 1 only at Amax = 3.0103 dB.
		console.log(\`Butterworth: eps = sqrt(10^(Amax/10) - 1) = \${design.eps.toFixed(4)}, pole circle at fp x eps^(\${FILTER_TYPE === 'highpass' ? '+' : '-'}1/n) = \${fp} x \${design.wcScale.toFixed(4)} = \${(design.wc / (2 * Math.PI)).toFixed(1)} Hz (the -3 dB frequency)\`);
	}
}

console.log();
console.log('='.repeat(72));
console.log('STAGES');
console.log('='.repeat(72));
const realized = design.stages.map((stage, i) => {
	const ov = CAP_OVERRIDES[i];

	if (stage.order === 1) {
		let r;
		if (stage.filterType === 'highpass') {
			r =
				ov && ov.C
					? designFirstOrderHighPassFromCap(stage.tau, ov.C, { resistorSeries: RESISTOR_SERIES })
					: designFirstOrderHighPass(stage.tau, { resistorSeries: RESISTOR_SERIES });
		} else {
			r =
				ov && ov.C
					? designFirstOrderLowPassFromCap(stage.tau, ov.C, { resistorSeries: RESISTOR_SERIES })
					: designFirstOrderLowPass(stage.tau, { resistorSeries: RESISTOR_SERIES });
		}
		console.log(\`stage \${i + 1} (1st order, \${stage.filterType}): tau = \${stage.tau.toExponential(4)} s\`);
		console.log(\`  R = \${r.components.R} ohm, C = \${r.components.C.toExponential(4)} F\`);
		console.log(\`  actual tau = \${r.actual.tau.toExponential(4)} s (\${(100 * (r.actual.tau - stage.tau) / stage.tau).toFixed(2)}%)\`);
		return r;
	}
	const f0 = stage.wn / (2 * Math.PI);
	console.log(\`stage \${i + 1} (\${stage.filterType}): f0 = \${f0.toFixed(1)} Hz, Q = \${stage.q.toFixed(4)}\`);

	let r;
	if (stage.filterType === 'highpass') {
		if (TOPOLOGY === 'sallenKey') {
			const auto = designSallenKeyHighPass(stage.wn, stage.q, { resistorSeries: RESISTOR_SERIES });
			r = ov && ov.C ? designSallenKeyHighPassFromCap(stage.wn, stage.q, ov.C, { resistorSeries: RESISTOR_SERIES }) : auto;
		} else {
			const auto = designMfbHighPass(stage.wn, stage.q, { resistorSeries: RESISTOR_SERIES });
			r = ov && ov.C ? designMfbHighPassFromCap(stage.wn, stage.q, ov.C, { resistorSeries: RESISTOR_SERIES }) : auto;
		}
	} else if (TOPOLOGY === 'sallenKey') {
		const auto = designSallenKeyLowPass(stage.wn, stage.q, { resistorSeries: RESISTOR_SERIES });
		if (ov && (ov.Ctop || ov.Cbottom)) {
			const Ctop = ov.Ctop || auto.components.Ctop;
			const Cbottom = ov.Cbottom || auto.components.Cbottom;
			const manual = designSallenKeyLowPassFromCaps(stage.wn, stage.q, Ctop, Cbottom, { resistorSeries: RESISTOR_SERIES });
			r = manual.ok ? manual : auto;
		} else {
			r = auto;
		}
	} else {
		const auto = designMfbLowPass(stage.wn, stage.q, { resistorSeries: RESISTOR_SERIES });
		if (ov && (ov.C1 || ov.C2)) {
			const C1 = ov.C1 || auto.components.C1;
			const C2 = ov.C2 || auto.components.C2;
			const manual = designMfbLowPassFromCaps(stage.wn, stage.q, C1, C2, { resistorSeries: RESISTOR_SERIES });
			if (manual.ok) {
				r = manual;
			} else {
				console.log(\`  note: the C1/C2 override cannot realize this Q (needs C1/C2 >= 8*Q^2), using the automatic search instead\`);
				r = auto;
			}
		} else {
			r = auto;
		}
	}
	for (const [name, value] of Object.entries(r.components)) {
		const isR = name.startsWith('R');
		console.log(\`  \${name} = \${isR ? value.toFixed(0) + ' ohm' : value.toExponential(4) + ' F'}\`);
	}
	const f0Actual = r.actual.wn / (2 * Math.PI);
	console.log(
		\`  actual f0 = \${f0Actual.toFixed(1)} Hz (\${(100 * (f0Actual - f0) / f0).toFixed(2)}%), Q = \${r.actual.q.toFixed(4)} (\${(100 * (r.actual.q - stage.q) / stage.q).toFixed(2)}%)\`
	);
	if (stage.filterType === 'highpass') {
		const sens = TOPOLOGY === 'sallenKey' ? SALLEN_KEY_HP_SENSITIVITY : MFB_HP_SENSITIVITY;
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(sens, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
	} else if (TOPOLOGY === 'mfb') {
		const sens = mfbSensitivity(r.components);
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(sens, 1).toFixed(2)}% (root-sum-square)\`);
	} else {
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(SALLEN_KEY_SENSITIVITY, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
	}
	return r;
});

if (FILTER_TYPE === 'bandstop') {
	console.log();
	console.log('='.repeat(72));
	console.log('SUMMING AMPLIFIER (combines the low-pass and high-pass branches above)');
	console.log('='.repeat(72));
	console.log(\`  Ra = Rb = Rf = \${SUMMING_R} ohm (any equal value works exactly)\`);
	console.log('  Vout = -(V_lp + V_hp)');
}

console.log();
console.log('='.repeat(72));
console.log('FREQUENCY RESPONSE (from the rounded, realized components)');
console.log('='.repeat(72));
if (FILTER_TYPE === 'bandpass') {
	for (const f of [fsl / 10, fsl, fl, Math.sqrt(fl * fh), fh, fsh, fsh * 10]) {
		const { db } = magnitudePhaseAt(realized, f);
		console.log(\`  \${f.toFixed(0).padStart(9)} Hz : \${db.toFixed(2).padStart(8)} dB\`);
	}
	const attnAtFsl = -magnitudePhaseAt(realized, fsl).db;
	const attnAtFsh = -magnitudePhaseAt(realized, fsh).db;
	console.log(\`\\nattenuation at fsl = \${attnAtFsl.toFixed(1)} dB, at fsh = \${attnAtFsh.toFixed(1)} dB (spec asks for >= \${Amin} dB on both): \${attnAtFsl >= Amin && attnAtFsh >= Amin ? 'OK' : 'NOT MET'}\`);
} else if (FILTER_TYPE === 'bandstop') {
	const lpBranch = realized.slice(0, design.lp.stages.length);
	const hpBranch = realized.slice(design.lp.stages.length);
	const branches = [lpBranch, hpBranch];
	for (const f of [fl / 10, fl, fsl, Math.sqrt(fsl * fsh), fsh, fh, fh * 10]) {
		const { db } = magnitudePhaseAtParallelSum(branches, f);
		console.log(\`  \${f.toFixed(0).padStart(9)} Hz : \${db.toFixed(2).padStart(8)} dB\`);
	}
	const attnAtFsl = -magnitudePhaseAtParallelSum(branches, fsl).db;
	const attnAtFsh = -magnitudePhaseAtParallelSum(branches, fsh).db;
	console.log(\`\\nattenuation at fsl = \${attnAtFsl.toFixed(1)} dB, at fsh = \${attnAtFsh.toFixed(1)} dB (spec asks for >= \${Amin} dB on both): \${attnAtFsl >= Amin && attnAtFsh >= Amin ? 'OK' : 'NOT MET'}\`);
} else {
	for (const f of [fp / 10, fp, Math.sqrt(fp * fs), fs, fs * 10]) {
		const { db } = magnitudePhaseAt(realized, f);
		console.log(\`  \${f.toFixed(0).padStart(9)} Hz : \${db.toFixed(2).padStart(8)} dB\`);
	}
	const attnAtFs = -magnitudePhaseAt(realized, fs).db;
	console.log(\`\\nattenuation at fs = \${attnAtFs.toFixed(1)} dB (spec asks for >= \${Amin} dB): \${attnAtFs >= Amin ? 'OK' : 'NOT MET'}\`);
}
`;
}

/**
 * What's left after this tool: simulate, build, measure. Shared between the
 * downloaded script's closing comment block and the page's own "Next steps"
 * section, so the two stay in sync.
 */
export const NEXT_STEPS = [
	{
		title: 'Simulate before you build',
		detail:
			'Every number above comes from an ideal op-amp: infinite gain-bandwidth, no slew rate limit. Drop the design into LTSpice (or any SPICE simulator) with the real op-amp model you plan to use (e.g. a TL082 .subckt) and rerun an AC sweep. Check that the model\'s gain-bandwidth is at least 10-20x your highest stage\'s f0 times that stage\'s gain - below that, the real op-amp starts rolling off before your filter does, and the passband/stopband numbers stop being accurate.'
	},
	{
		title: 'Build and test one stage at a time',
		detail:
			"Confirm each stage's measured f0 and Q against this design's actual values before wiring the next stage on, instead of assembling the whole cascade and hoping."
	},
	{
		title: 'Match impedances between stages',
		detail:
			'The output impedance of one stage should stay well below the input impedance of the next (Zout << Zin), otherwise the second stage loads the first and both f0 and Q drift from what was computed. This matters most between the last filter stage and whatever it feeds.'
	},
	{
		title: 'Measure a real Bode plot',
		detail:
			'Compare it to the simulated response above: a handful of points swept from fp/10 to fs*10 with a function generator and a scope (or an audio analyzer) is enough to catch a wiring mistake or a component that is the wrong value.'
	},
	{
		title: 'If the measured response drifts, check sensitivity first',
		detail:
			'The sensitivity numbers above say how much a single component being off by 1% moves Q - that is usually the first place to look before assuming the design itself is wrong.'
	}
];

function nextStepsComment() {
	const lines = [
		'// =====================================================================',
		'// NEXT STEPS - this script only gets you a paper design',
		'// ====================================================================='
	];
	NEXT_STEPS.forEach((step, i) => {
		lines.push('//');
		lines.push(`// ${i + 1}. ${step.title}.`);
		for (const line of wrapComment(step.detail, 74)) lines.push(`//    ${line}`);
	});
	return lines.join('\n') + '\n';
}

function wrapComment(text, width) {
	const words = text.split(' ');
	const lines = [];
	let line = '';
	for (const word of words) {
		if ((line + ' ' + word).trim().length > width) {
			lines.push(line.trim());
			line = word;
		} else {
			line = (line + ' ' + word).trim();
		}
	}
	if (line) lines.push(line);
	return lines;
}

/**
 * Builds the full standalone script for the design currently shown on the
 * page: same math, same component search, same order and any manual
 * capacitor choices the user picked.
 */
export function generateScript({
	amaxDb,
	aminDb,
	fp,
	fs,
	fl,
	fh,
	fsl,
	fsh,
	filterType,
	response,
	topology,
	order,
	orderHp,
	orderLp,
	capOverrides
}) {
	const chunks = [
		header(filterType),
		paramsBlock({
			amaxDb,
			aminDb,
			fp,
			fs,
			fl,
			fh,
			fsl,
			fsh,
			filterType,
			response,
			topology,
			order,
			orderHp,
			orderLp,
			capOverrides
		}),
		'// ===================================================================== \n// ENGINE - same code the web tool runs\n// =====================================================================\n',
		inline(eseriesSrc),
		inline(formatSrc),
		inline(orderSrc),
		inline(stagesSrc),
		inline(mfbSrc),
		inline(mfbHighPassSrc),
		inline(sallenKeySrc),
		inline(sallenKeyHighPassSrc),
		inline(firstOrderSrc),
		inline(firstOrderHighPassSrc),
		inline(bodeSrc),
		inline(sensitivitySrc),
		reportBlock(),
		nextStepsComment()
	];
	return chunks.join('\n\n');
}
