import approximationsSrc from './approximations.js?raw';
import bodeSrc from './bode.js?raw';
import eseriesSrc from './eseries.js?raw';
import firstOrderSrc from './firstOrder.js?raw';
import firstOrderHighPassSrc from './firstOrderHighPass.js?raw';
import formatSrc from './format.js?raw';
import mfbSrc from './mfb.js?raw';
import mfbHighPassSrc from './mfbHighPass.js?raw';
import orderSrc from './order.js?raw';
import sallenKeySrc from './sallenKey.js?raw';
import sallenKeyHighPassSrc from './sallenKeyHighPass.js?raw';
import sensitivitySrc from './sensitivity.js?raw';
import stagesSrc from './stages.js?raw';
import towThomasSrc from './towThomas.js?raw';
import boctorSrc from './boctor.js?raw';

/**
 * Turns one of this file's own modules into a plain script chunk: strips
 * the `import`/`export` keywords (the download is a single file, so every
 * function just lives in one shared scope) but keeps everything else
 * verbatim. This is the actual, tested engine source - not a re-typed copy
 * of it - so the download can never drift from what the page itself computes.
 */
function inline(src) {
	return src
		.split('\n')
		.filter((line) => !/^import\s/.test(line))
		.join('\n')
		.replace(/^export\s+/gm, '')
		.trim();
}

const TYPE_LABEL = {
	lowpass: 'low-pass',
	highpass: 'high-pass',
	bandpass: 'band-pass',
	bandstop: 'band-stop'
};

function header(filterType) {
	return `/**
 * Active ${TYPE_LABEL[filterType] ?? 'low-pass'} filter design, generated by rbt56.com/tools/filter-design/
 *
 * Self-contained: every function below is the same code the web tool runs,
 * just copied out of its ES modules into one plain script. Change the
 * PARAMETERS block and rerun with:
 *
 *   node filter-design.js
 *
 * Everything downstream of PARAMETERS recomputes from scratch, same as the
 * page does live as its form is edited.
 */
`;
}

function paramsBlock({ amaxDb, aminDb, amaxDbHp, aminDbHp, amaxDbLp, aminDbLp, fp, fs, fl, fh, fsl, fsh, filterType, response, responseHp, responseLp, topology, topologyHp, topologyLp, order, orderHp, orderLp, capOverrides, resistorStock, resistorPairs, capacitorStock }) {
	const hasOverrides = capOverrides && Object.keys(capOverrides).length > 0;
	return `// =====================================================================
// PARAMETERS - the only block meant to be edited
// =====================================================================

const Amax = ${amaxDb};              // dB, max attenuation allowed in the passband ('lowpass', 'highpass')
const Amin = ${aminDb};              // dB, min attenuation required in the stopband ('lowpass', 'highpass')
// 'bandpass' and 'bandstop' are two filters, and each side has its own Amax
const AMAX_HP = ${amaxDbHp ?? amaxDb};           // dB, the high-pass side's Amax (at fl for a band-pass, fh for a band-stop)
const AMAX_LP = ${amaxDbLp ?? amaxDb};           // dB, the low-pass side's Amax (at fh for a band-pass, fl for a band-stop)
// A band-pass has two stopbands, one per side, so each side has its own
// Amin as well. A band-stop's one stopband keeps Amin above: both branches
// leak into all of it, so neither could be held to more than the other.
const AMIN_HP = ${aminDbHp ?? aminDb};          // dB, band-pass: the high-pass side's Amin, at fsl
const AMIN_LP = ${aminDbLp ?? aminDb};          // dB, band-pass: the low-pass side's Amin, at fsh
const FILTER_TYPE = ${JSON.stringify(filterType)}; // 'lowpass', 'highpass', 'bandpass' or 'bandstop'
// Responses: 'butterworth', 'chebyshev', 'legendre', 'bessel',
// 'inverseChebyshev' or 'elliptic'.
const RESPONSE  = ${JSON.stringify(response)};  // used by 'lowpass' and 'highpass'
const RESPONSE_HP = ${JSON.stringify(responseHp ?? response)};  // band-pass / band-stop: the high-pass side's
const RESPONSE_LP = ${JSON.stringify(responseLp ?? response)};  // band-pass / band-stop: the low-pass side's
// 'mfb', 'sallenKey' or 'towThomas'. The elliptic and inverse Chebyshev
// responses need 'towThomas': their stages with zeros are Tow-Thomas notch
// stages, which no other wiring here can build, and the script stops on
// any other topology with them, as the page does.
const TOPOLOGY  = ${JSON.stringify(topology)};    // used by 'lowpass' and 'highpass'
const TOPOLOGY_HP = ${JSON.stringify(topologyHp ?? topology)};  // band-pass / band-stop: the high-pass side's
const TOPOLOGY_LP = ${JSON.stringify(topologyLp ?? topology)};  // band-pass / band-stop: the low-pass side's
const RESISTOR_SERIES = ${JSON.stringify(resistorStock ?? 'E24')};
// 'E24' or 'E96' for a full preferred series, or an explicit array of
// ohm values to design against only what is actually in the drawer.
const RESISTOR_PAIRS = ${resistorPairs ? 'true' : 'false'};   // with an array above: a resistor that sets f0, Q or a zero may be two in series
const CAPACITORS = ${JSON.stringify(capacitorStock ?? null)};
// null for the usual E6/E12 capacitor grids, or an array of farad values.
const SUMMING_R = 10000;          // ohms, band-stop's summing amplifier (any equal value works)

// Used when FILTER_TYPE is 'lowpass' or 'highpass':
const fp   = ${fp};           // Hz, passband edge (the higher edge for a high-pass)
const fs   = ${fs};           // Hz, stopband edge (the lower edge for a high-pass)
const ORDER = ${order};                 // set to null to use the minimum order that meets the spec

// Used when FILTER_TYPE is 'bandpass' (a high-pass section cascaded with a
// low-pass section - see designBandPass below) or 'bandstop' (a low-pass
// branch and a high-pass branch summed instead - see designBandStop).
// Band-pass needs fsl < fl < fh < fsh; band-stop needs fl < fsl < fsh < fh.
const fl   = ${fl};           // Hz
const fh   = ${fh};           // Hz
const fsl  = ${fsl};           // Hz
const fsh  = ${fsh};           // Hz
const ORDER_HP = ${orderHp};                 // set to null to use the minimum order for the high-pass section/branch
const ORDER_LP = ${orderLp};                 // set to null to use the minimum order for the low-pass section/branch

// Capacitor values (farads) to use instead of the automatic search, keyed
// by stage index (0-based, same order as the STAGES report below). Leave a
// stage out of this object to keep searching automatically for it. Needs
// C1 and C2 for an MFB stage, Ctop and Cbottom for Sallen-Key, C for a
// first-order (leftover, odd-n) stage, a Tow-Thomas stage or a notch stage.
const CAP_OVERRIDES = ${hasOverrides ? JSON.stringify(capOverrides, null, 2) : '{}'};
`;
}

function reportBlock() {
	return `// =====================================================================
// REPORT
// =====================================================================

// zeros in the stopband take a notch stage, and only the Tow-Thomas biquad
// has one: the side (or the filter) with such a response must be Tow-Thomas
const BAND = FILTER_TYPE === 'bandpass' || FILTER_TYPE === 'bandstop';
const topologyOf = (side) => (BAND ? (side === 'highpass' ? TOPOLOGY_HP : TOPOLOGY_LP) : TOPOLOGY);
for (const [response, side, name] of BAND ? [[RESPONSE_HP, 'highpass', 'TOPOLOGY_HP'], [RESPONSE_LP, 'lowpass', 'TOPOLOGY_LP']] : [[RESPONSE, FILTER_TYPE, 'TOPOLOGY']]) {
	if (RESPONSES[response].zeros && !['towThomas', 'boctor'].includes(topologyOf(side))) {
		throw new Error(\`\${RESPONSES[response].label} needs Tow-Thomas or Boctor notch stages: set \${name} = 'towThomas'\`);
	}
}

console.log('='.repeat(72));
console.log('ORDER');
console.log('='.repeat(72));

/** One side's order, printed with where it comes from. */
function orderFor(label, response, k, forced, amax = Amax, amin = Amin) {
	const min = minimumOrder(response, amax, amin, k);
	if (min.tried) {
		console.log(\`\${label}: \${RESPONSES[response].label}, k = \${k.toFixed(4)}, no closed formula: loss at the stopband edge by order \${min.tried.map((t) => \`n=\${t.n}: \${t.loss.toFixed(1)} dB\`).join(', ')}\`);
	} else {
		console.log(\`\${label}: \${RESPONSES[response].label}, k = \${k.toFixed(4)}, minimum order >= \${min.value.toFixed(4)}\`);
	}
	const n = forced ?? min.n;
	if (n === null) throw new Error(\`\${RESPONSES[response].label} does not reach Amin = \${amin} dB at any order up to \${SEARCH_LIMIT}: loosen the spec or pick a steeper response\`);
	console.log(\`  -> using n = \${n}\`);
	return n;
}

let design;
if (FILTER_TYPE === 'bandpass') {
	console.log(\`spec: bandpass (fl=\${fl} fh=\${fh} fsl=\${fsl} fsh=\${fsh} Hz), high-pass side Amax=\${AMAX_HP} dB Amin=\${AMIN_HP} dB, low-pass side Amax=\${AMAX_LP} dB Amin=\${AMIN_LP} dB\`);
	const nHp = orderFor('high-pass side', RESPONSE_HP, transitionRatio(fsl, fl), ORDER_HP, AMAX_HP, AMIN_HP);
	const nLp = orderFor('low-pass side', RESPONSE_LP, transitionRatio(fh, fsh), ORDER_LP, AMAX_LP, AMIN_LP);
	design = designBandPass({ responseHp: RESPONSE_HP, responseLp: RESPONSE_LP, amaxDbHp: AMAX_HP, aminDbHp: AMIN_HP, amaxDbLp: AMAX_LP, aminDbLp: AMIN_LP, fl, fh, fsl, fsh, orderHigh: nHp, orderLow: nLp });
} else if (FILTER_TYPE === 'bandstop') {
	console.log(\`spec: bandstop (fl=\${fl} fsl=\${fsl} fsh=\${fsh} fh=\${fh} Hz), Amin=\${Amin} dB across the stopband, low-pass branch Amax=\${AMAX_LP} dB, high-pass branch Amax=\${AMAX_HP} dB\`);
	const nLp = orderFor('low-pass branch', RESPONSE_LP, transitionRatio(fl, fsl), ORDER_LP, AMAX_LP, Amin);
	const nHp = orderFor('high-pass branch', RESPONSE_HP, transitionRatio(fsh, fh), ORDER_HP, AMAX_HP, Amin);
	design = designBandStop({ responseHp: RESPONSE_HP, responseLp: RESPONSE_LP, amaxDbHp: AMAX_HP, amaxDbLp: AMAX_LP, aminDb: Amin, fl, fh, fsl, fsh, orderHigh: nHp, orderLow: nLp });
} else {
	console.log(\`spec: Amax=\${Amax} dB at \${fp} Hz, Amin=\${Amin} dB at \${fs} Hz, \${FILTER_TYPE}\`);
	const k = FILTER_TYPE === 'highpass' ? transitionRatio(fs, fp) : transitionRatio(fp, fs);
	const n = orderFor(FILTER_TYPE === 'highpass' ? 'k = fs/fp' : 'k = fp/fs', RESPONSE, k, ORDER);
	design =
		FILTER_TYPE === 'highpass'
			? designHighPass({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fp, fs, order: n })
			: designLowPass({ response: RESPONSE, amaxDb: Amax, aminDb: Amin, fp, fs, order: n });
	if (RESPONSE === 'butterworth') {
		// Where Amax reaches the components: the pole circle (= the -3 dB point)
		// sits at fp * eps^(-1/n) for a low-pass, fp * eps^(+1/n) for a high-pass,
		// so that exactly Amax dB is lost at fp. eps = 1 only at Amax = 3.0103 dB.
		console.log(\`Butterworth: eps = sqrt(10^(Amax/10) - 1) = \${design.eps.toFixed(4)}, pole circle at fp x eps^(\${FILTER_TYPE === 'highpass' ? '+' : '-'}1/n) = \${fp} x \${design.wcScale.toFixed(4)} = \${(design.wc / (2 * Math.PI)).toFixed(1)} Hz (the -3 dB frequency)\`);
	}
	if (design.prototype && Number.isFinite(design.prototype.aminReached)) {
		console.log(\`the extra order goes to the stopband: at least \${design.prototype.aminReached.toFixed(2)} dB across it (Amin = \${Amin} dB)\`);
	}
}

console.log();
console.log('='.repeat(72));
console.log('STAGES');
console.log('='.repeat(72));
const OPTS = { resistorSeries: RESISTOR_SERIES, capacitors: CAPACITORS, pairs: RESISTOR_PAIRS };
// a resistor built from two in series is printed with its two parts
const ohms = (value) => {
	const pair = RESISTOR_PAIRS ? seriesPair(value, RESISTOR_SERIES) : null;
	return \`\${value.toFixed(0)} ohm\${pair ? \` (\${Number(pair[0].toPrecision(6))} + \${Number(pair[1].toPrecision(6))} in series)\` : ''}\`;
};
const printParts = (r) => {
	for (const [name, value] of Object.entries(r.components)) {
		const isR = /^[Rr]/.test(name);
		console.log(\`  \${name} = \${isR ? ohms(value) : value.toExponential(4) + ' F'}\`);
	}
};
const realized = design.stages.map((stage, i) => {
	const ov = CAP_OVERRIDES[i];

	if (stage.order === 1) {
		let r;
		if (stage.filterType === 'highpass') {
			r = ov && ov.C ? designFirstOrderHighPassFromCap(stage.tau, ov.C, OPTS) : designFirstOrderHighPass(stage.tau, OPTS);
		} else {
			r = ov && ov.C ? designFirstOrderLowPassFromCap(stage.tau, ov.C, OPTS) : designFirstOrderLowPass(stage.tau, OPTS);
		}
		console.log(\`stage \${i + 1} (1st order, \${stage.filterType}): tau = \${stage.tau.toExponential(4)} s\`);
		console.log(\`  R = \${RESISTOR_PAIRS && seriesPair(r.components.R, RESISTOR_SERIES) ? ohms(r.components.R) : r.components.R + ' ohm'}, C = \${r.components.C.toExponential(4)} F\`);
		console.log(\`  actual tau = \${r.actual.tau.toExponential(4)} s (\${(100 * (r.actual.tau - stage.tau) / stage.tau).toFixed(2)}%)\`);
		return r;
	}
	const f0 = stage.wn / (2 * Math.PI);

	if (Number.isFinite(stage.wz)) {
		// A finite zero uses the selected notch network.
		const fz = stage.wz / (2 * Math.PI);
		const lowSide = stage.filterType === 'lowpass';
		console.log(\`stage \${i + 1} (\${stage.filterType} notch): f0 = \${f0.toFixed(1)} Hz, Q = \${stage.q.toFixed(4)}, zero at fz = \${fz.toFixed(1)} Hz\`);
		const notch = topologyOf(stage.filterType) === 'boctor' ? designBoctorNotch : designTowThomasNotch;
		const fromCap = topologyOf(stage.filterType) === 'boctor' ? designBoctorNotchFromCap : designTowThomasNotchFromCap;
		let notchOpts = { ...OPTS, lowSide };
		let auto = notch(stage.wn, stage.q, stage.wz, notchOpts);
		if (!auto && topologyOf(stage.filterType) === 'boctor') {
			notchOpts = { resistorSeries: 'E24', capacitors: null, lowSide };
			auto = notch(stage.wn, stage.q, stage.wz, notchOpts);
			if (auto) console.log('  Stock cannot realize this section; using the full E24/E6 grid, as on the page.');
		}
		const edited = ov && ov.C ? fromCap(stage.wn, stage.q, stage.wz, ov.C, notchOpts) : null;
		const r = edited && edited.ok !== false ? edited : auto;
		if (!r) throw new Error('This Boctor section is not realizable. Select Tow-Thomas or change the specification.');
		printParts(r);
		const f0Actual = r.actual.wn / (2 * Math.PI);
		const fzActual = r.actual.wz / (2 * Math.PI);
		console.log(
			\`  actual f0 = \${f0Actual.toFixed(1)} Hz (\${(100 * (f0Actual - f0) / f0).toFixed(2)}%), Q = \${r.actual.q.toFixed(4)} (\${(100 * (r.actual.q - stage.q) / stage.q).toFixed(2)}%), fz = \${fzActual.toFixed(1)} Hz (\${(100 * (fzActual - fz) / fz).toFixed(2)}%)\`
		);
		console.log('  numerator s coefficient = ' + (r.actual.numeratorS ?? 0));
		console.log(lowSide ? \`  DC gain = \${r.actual.dcGain.toFixed(4)} (including component rounding)\` : \`  gain above the zero = \${r.actual.gain.toFixed(4)}\`);
		if (topologyOf(stage.filterType) !== 'boctor') console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(TOW_THOMAS_NOTCH_SENSITIVITY, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
		return r;
	}

	console.log(\`stage \${i + 1} (\${stage.filterType}): f0 = \${f0.toFixed(1)} Hz, Q = \${stage.q.toFixed(4)}\`);
	const TOPO = topologyOf(stage.filterType);
	let r;
	if (stage.filterType === 'highpass') {
		if (TOPO === 'towThomas' || TOPO === 'boctor') {
			r = ov && ov.C ? designTowThomasHighPassFromCap(stage.wn, stage.q, ov.C, OPTS) : designTowThomasHighPass(stage.wn, stage.q, OPTS);
		} else if (TOPO === 'sallenKey') {
			r = ov && ov.C ? designSallenKeyHighPassFromCap(stage.wn, stage.q, ov.C, OPTS) : designSallenKeyHighPass(stage.wn, stage.q, OPTS);
		} else {
			r = ov && ov.C ? designMfbHighPassFromCap(stage.wn, stage.q, ov.C, OPTS) : designMfbHighPass(stage.wn, stage.q, OPTS);
		}
	} else if (TOPO === 'towThomas' || TOPO === 'boctor') {
		r = ov && ov.C ? designTowThomasLowPassFromCap(stage.wn, stage.q, ov.C, OPTS) : designTowThomasLowPass(stage.wn, stage.q, OPTS);
	} else if (TOPO === 'sallenKey') {
		const auto = designSallenKeyLowPass(stage.wn, stage.q, OPTS);
		if (ov && (ov.Ctop || ov.Cbottom)) {
			const manual = designSallenKeyLowPassFromCaps(stage.wn, stage.q, ov.Ctop || auto.components.Ctop, ov.Cbottom || auto.components.Cbottom, OPTS);
			r = manual.ok ? manual : auto;
		} else {
			r = auto;
		}
	} else {
		const auto = designMfbLowPass(stage.wn, stage.q, OPTS);
		if (ov && (ov.C1 || ov.C2)) {
			const manual = designMfbLowPassFromCaps(stage.wn, stage.q, ov.C1 || auto.components.C1, ov.C2 || auto.components.C2, OPTS);
			if (manual.ok) {
				r = manual;
			} else {
				console.log(\`  note: the C1/C2 override cannot realize this Q (needs C1/C2 >= 8*Q^2), using the automatic search instead\`);
				r = auto;
			}
		} else {
			r = auto;
		}
	}
	printParts(r);
	const f0Actual = r.actual.wn / (2 * Math.PI);
	console.log(
		\`  actual f0 = \${f0Actual.toFixed(1)} Hz (\${(100 * (f0Actual - f0) / f0).toFixed(2)}%), Q = \${r.actual.q.toFixed(4)} (\${(100 * (r.actual.q - stage.q) / stage.q).toFixed(2)}%)\`
	);
	if (stage.filterType === 'highpass') {
		const sens = TOPO === 'towThomas' || TOPO === 'boctor' ? TOW_THOMAS_HP_SENSITIVITY : TOPO === 'sallenKey' ? SALLEN_KEY_HP_SENSITIVITY : MFB_HP_SENSITIVITY;
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(sens, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
	} else if (TOPO === 'towThomas' || TOPO === 'boctor') {
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(TOW_THOMAS_SENSITIVITY, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
	} else if (TOPO === 'mfb') {
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(mfbSensitivity(r.components), 1).toFixed(2)}% (root-sum-square)\`);
	} else {
		console.log(\`  Q sensitivity to 1% component error: \${worstCaseQError(SALLEN_KEY_SENSITIVITY, 1).toFixed(2)}% (root-sum-square, fixed for this topology)\`);
	}
	return r;
});

// the band-stop's two branches and how the combiner weighs them
let branches = null;
let weights = null;
if (FILTER_TYPE === 'bandstop') {
	branches = [realized.slice(0, design.lp.stages.length), realized.slice(design.lp.stages.length)];
	const choice = combinerChoice(branches, fsl, fsh);
	const lpGain = Math.abs(branchDcGain(branches[0]));
	const parts = combinerDesign(choice.mode, SUMMING_R, lpGain, (v) => nearestResistor(v, RESISTOR_SERIES));
	weights = parts.weights;
	console.log();
	console.log('='.repeat(72));
	console.log(\`  notch centre \${choice.centreHz.toFixed(0)} Hz: plain sum \${choice.sumDb.toFixed(1)} dB, difference \${choice.differenceDb.toFixed(1)} dB -> \${choice.mode}\`);
	console.log(\`  branch signs: low-pass \${branchSign(branches[0]) > 0 ? '+1' : '-1'} (order \${branchOrder(branches[0])}), high-pass \${branchSign(branches[1]) > 0 ? '+1' : '-1'} (order \${branchOrder(branches[1])})\`);
	console.log(choice.mode === 'difference' ? 'DIFFERENCE AMPLIFIER (the deeper notch of the two combiners)' : 'SUMMING AMPLIFIER (combines the low-pass and high-pass branches above)');
	console.log('='.repeat(72));
	for (const [name, value] of Object.entries(parts.resistors)) console.log(\`  \${name} = \${value.toFixed(0)} ohm\`);
	if (Math.abs(lpGain - 1) > 1e-6) console.log(\`  the low-pass branch passes DC at \${lpGain.toFixed(4)} (a notch stage's rounded Cin), so its input resistor is scaled by that factor\`);
	console.log(choice.mode === 'difference' ? '  Vout = V_hp - V_lp' : '  Vout = -(V_lp + V_hp)');
}

console.log();
console.log('='.repeat(72));
console.log('FREQUENCY RESPONSE (from the rounded, realized components)');
console.log('='.repeat(72));
const gainDb = (f) => (FILTER_TYPE === 'bandstop' ? magnitudePhaseAtParallelSum(branches, f, weights).db : magnitudePhaseAt(realized, f).db);
// each stretch of stopband carries the Amin it answers to: a band-pass's
// lower stopband is its high-pass side's, its upper one the low-pass side's
const bands = {
	lowpass: { pass: [[fp / 100, fp]], stop: [[fs, fs * 100, Amin]], points: [fp / 10, fp, Math.sqrt(fp * fs), fs, fs * 10] },
	highpass: { pass: [[fp, fp * 100]], stop: [[fs / 100, fs, Amin]], points: [fs / 10, fs, Math.sqrt(fp * fs), fp, fp * 10] },
	bandpass: { pass: [[fl, fh]], stop: [[fsl / 100, fsl, AMIN_HP], [fsh, fsh * 100, AMIN_LP]], points: [fsl / 10, fsl, fl, Math.sqrt(fl * fh), fh, fsh, fsh * 10] },
	bandstop: { pass: [[fl / 100, fl], [fh, fh * 100]], stop: [[fsl, fsh, Amin]], points: [fl / 10, fl, fsl, Math.sqrt(fsl * fsh), fsh, fh, fh * 10] }
}[FILTER_TYPE];
for (const f of bands.points) console.log(\`  \${f.toFixed(0).padStart(9)} Hz : \${gainDb(f).toFixed(2).padStart(8)} dB\`);
// Amax and Amin count from the top of the passband (an even-order Chebyshev
// or elliptic ripples above its DC gain), and the stopband is searched over
// its whole width (an elliptic or inverse Chebyshev bounces between zeros)
const scan = (ranges) => {
	const out = [];
	for (const [a, b] of ranges) for (let i = 0; i <= 600; i++) out.push(a * (b / a) ** (i / 600));
	return out;
};
const top = Math.max(...scan(bands.pass).map(gainDb));
// the point with the least margin over its own Amin
let worst = { db: Infinity, f: 0, amin: Amin, margin: Infinity };
for (const [a, b, amin] of bands.stop) {
	for (const f of scan([[a, b]])) {
		const att = top - gainDb(f);
		if (att - amin < worst.margin) worst = { db: att, f, amin, margin: att - amin };
	}
}
console.log(\`\\npassband top \${top.toFixed(2)} dB; least attenuation in the stopband \${worst.db.toFixed(1)} dB at \${worst.f.toFixed(0)} Hz (spec asks for >= \${worst.amin} dB there): \${worst.margin >= 0 ? 'OK' : 'NOT MET'}\`);
`;
}

/**
 * What's left after this tool: simulate, build, measure. Shared between the
 * downloaded script's closing comment block and the page's own "Next steps"
 * section, so the two stay in sync.
 */
export const NEXT_STEPS = [
	{
		title: 'Simulate before building',
		detail:
			"Every number above comes from an ideal op-amp: infinite gain-bandwidth, no slew rate limit. The LTspice download runs the design with the op-amp picked next to it (a TL082 or LM741 model, or the single-pole one), so run its AC sweep with the part that will be built. That part's gain-bandwidth should be well above the sharpest stage's needs: at least 100 times its Q times its f0 as a rule, a few hundred times for a Tow-Thomas stage (the topology note in panel 04 gives the figure for this design). Below that it rolls off before the filter does, and the passband and stopband figures stop holding."
	},
	{
		title: 'Build and test one stage at a time',
		detail:
			"Confirm each stage's measured f0 and Q against this design's actual values before wiring the next stage on, instead of assembling the whole cascade and hoping."
	},
	{
		title: 'Match impedances between stages',
		detail:
			'The output impedance of one stage should stay well below the input impedance of the next (Zout << Zin), otherwise the second stage loads the first and both f0 and Q drift from what was computed. This matters most between the last filter stage and whatever it feeds.'
	},
	{
		title: 'Measure a real Bode plot',
		detail:
			'Compare it to the simulated response above: a handful of points swept from fp/10 to fs*10 with a function generator and a scope (or an audio analyzer) is enough to catch a wiring mistake or a component that is the wrong value.'
	},
	{
		title: 'If the measured response drifts, check sensitivity first',
		detail:
			'The sensitivity numbers above say how much a single component being off by 1% moves Q: that is usually the first place to look before assuming the design itself is wrong.'
	}
];

function nextStepsComment() {
	const lines = [
		'// =====================================================================',
		'// NEXT STEPS: this script only makes a paper design',
		'// ====================================================================='
	];
	NEXT_STEPS.forEach((step, i) => {
		lines.push('//');
		lines.push(`// ${i + 1}. ${step.title}.`);
		for (const line of wrapComment(step.detail, 74)) lines.push(`//    ${line}`);
	});
	return lines.join('\n') + '\n';
}

function wrapComment(text, width) {
	const words = text.split(' ');
	const lines = [];
	let line = '';
	for (const word of words) {
		if ((line + ' ' + word).trim().length > width) {
			lines.push(line.trim());
			line = word;
		} else {
			line = (line + ' ' + word).trim();
		}
	}
	if (line) lines.push(line);
	return lines;
}

/**
 * Builds the full standalone script for the design currently shown on the
 * page: same math, same component search, same order and any manual
 * capacitor choices the user picked.
 */
export function generateScript({
	amaxDb,
	aminDb,
	amaxDbHp = amaxDb,
	aminDbHp = aminDb,
	amaxDbLp = amaxDb,
	aminDbLp = aminDb,
	fp,
	fs,
	fl,
	fh,
	fsl,
	fsh,
	filterType,
	response,
	responseHp = response,
	responseLp = response,
	topology,
	topologyHp = topology,
	topologyLp = topology,
	order,
	orderHp,
	orderLp,
	capOverrides,
	resistorStock = null,
	resistorPairs = false,
	capacitorStock = null
}) {
	const chunks = [
		header(filterType),
		paramsBlock({
			amaxDb,
			aminDb,
			amaxDbHp,
			aminDbHp,
			amaxDbLp,
			aminDbLp,
			fp,
			fs,
			fl,
			fh,
			fsl,
			fsh,
			filterType,
			response,
			responseHp,
			responseLp,
			topology,
			topologyHp,
			topologyLp,
			order,
			orderHp,
			orderLp,
			capOverrides,
			resistorStock,
			resistorPairs,
			capacitorStock
		}),
		'// ===================================================================== \n// ENGINE - same code the web tool runs\n// =====================================================================\n',
		inline(eseriesSrc),
		inline(formatSrc),
		inline(orderSrc),
		inline(approximationsSrc),
		inline(stagesSrc),
		inline(mfbSrc),
		inline(mfbHighPassSrc),
		inline(sallenKeySrc),
		inline(sallenKeyHighPassSrc),
		inline(towThomasSrc),
		inline(boctorSrc),
		inline(firstOrderSrc),
		inline(firstOrderHighPassSrc),
		inline(bodeSrc),
		inline(sensitivitySrc),
		reportBlock(),
		nextStepsComment()
	];
	return chunks.join('\n\n');
}
